# Generated by Django 4.1.5 on 2023-01-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('idm', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('ph', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
