# Generated by Django 4.1.5 on 2023-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetails1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('security_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='customerdetails',
        ),
    ]
