# Generated by Django 4.1.5 on 2023-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customerdetails1_delete_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
