# Generated by Django 4.1.5 on 2023-02-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_user_id_profile_cartid_wishlist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cartid',
        ),
    ]
